import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — LinkedIn Profile Optimizer",
  description:
    "Terms of service for LinkedIn Profile Optimizer. Read our usage terms, payment policy, and legal disclaimers.",
  alternates: {
    canonical: "https://linkedin-profile-optimizer.vercel.app/terms",
  },
  robots: { index: false, follow: false },
};

export default function Terms() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white rounded-2xl border p-8 space-y-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
            <p className="text-sm text-gray-400">Last updated: June 2025</p>
          </div>

          <p className="text-gray-600">
            These Terms of Service ("Terms") govern your use of the LinkedIn Profile Optimizer
            website and services ("Service"). By accessing or using our Service, you agree to
            be bound by these Terms.
          </p>

          {[
            {
              title: "1. Description of Service",
              body: "LinkedIn Profile Optimizer provides an AI-powered tool that analyzes a user's LinkedIn headline and About section to produce a profile strength score, identify missing keywords, and offer optimization suggestions. An optional paid tier provides a fully rewritten headline, About section, and recommended skills list for a one-time fee of $5.",
            },
            {
              title: "2. Eligibility",
              body: "You must be at least 18 years of age to use this Service. By using the Service, you represent that you are at least 18 years old and have the legal capacity to enter into these Terms.",
            },
            {
              title: "3. Use of the Service",
              body: "You agree to use the Service only for lawful purposes. You agree not to submit false or misleading content, attempt to circumvent security features, use bots or scrapers to access the Service, or resell the Service without written consent.",
            },
            {
              title: "4. Intellectual Property",
              body: "The Service and its content are owned by us and protected by applicable intellectual property laws. You retain ownership of the profile content you submit. By submitting content, you grant us a limited, non-exclusive license to process it for the purpose of providing the Service.",
            },
            {
              title: "5. No Career Guarantees",
              body: "We do not guarantee that using our Service will result in job interviews, offers, or any particular career outcome. Profile scores, keyword suggestions, and optimized content are generated by AI and provided for informational and enhancement purposes only. Hiring decisions are made by employers, not by our Service.",
            },
            {
              title: "6. Accuracy of AI-Generated Content",
              body: "Our Service uses AI language models to generate analysis and content. While we strive for accuracy, AI-generated content may contain errors or inaccuracies. You are responsible for reviewing all AI-generated content before using it. We recommend treating the output as a strong starting point that may benefit from personal refinement.",
            },
            {
              title: "7. Payments and Refunds",
              body: "The profile optimization service is available for a one-time payment of $5. Payments are processed securely through Lemon Squeezy. Because the optimization is delivered instantly as a digital product, all sales are final and non-refundable, except where required by applicable law. If you experience a technical issue preventing delivery, please contact us at bqtools92@gmail.com.",
            },
            {
              title: "8. Limitation of Liability",
              body: "To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid us in the 30 days preceding the claim.",
            },
            {
              title: "9. Disclaimer of Warranties",
              body: 'The Service is provided "as is" and "as available" without warranties of any kind. We expressly disclaim all warranties, including warranties of merchantability, fitness for a particular purpose, and non-infringement.',
            },
            {
              title: "10. Not Affiliated with LinkedIn",
              body: "LinkedIn Profile Optimizer is an independent tool and is not affiliated with, endorsed by, or connected to LinkedIn Corporation or Microsoft in any way. LinkedIn is a registered trademark of LinkedIn Corporation.",
            },
            {
              title: "11. Changes to Terms",
              body: 'We reserve the right to modify these Terms at any time. Changes are effective immediately upon posting. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms.',
            },
            {
              title: "12. Contact",
              body: "bqtools92@gmail.com",
            },
          ].map((section, i) => (
            <div key={i}>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">{section.title}</h2>
              <p className={`text-gray-600 ${i === 11 ? "font-semibold text-gray-900" : ""}`}>
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
