import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — AI Interview Prep",
  description:
    "Terms of service for AI Interview Prep. Read our usage terms, payment policy, and legal disclaimers.",
  alternates: {
    canonical: "https://interview-prep-six-gules.vercel.app/terms",
  },
  robots: { index: false, follow: false },
};

export default function Terms() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white rounded-2xl border p-8 space-y-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              Terms of Service
            </h1>
            <p className="text-sm text-gray-400">Last updated: June 2025</p>
          </div>

          <p className="text-gray-600">
            These Terms of Service (&quot;Terms&quot;) govern your use of the AI Interview
            Prep website and services (&quot;Service&quot;). By accessing or using our
            Service, you agree to be bound by these Terms.
          </p>

          {[
            {
              title: "1. Description of Service",
              body: "AI Interview Prep provides an AI-powered tool that generates tailored interview questions and STAR method answers from a job description. A free tier provides 3 sample questions. An optional paid tier provides 15 full questions with STAR answers and follow-up tips for a one-time fee of $19.",
            },
            {
              title: "2. Eligibility",
              body: "You must be at least 18 years of age to use this Service. By using the Service, you represent that you are at least 18 years old and have the legal capacity to enter into these Terms.",
            },
            {
              title: "3. Use of the Service",
              body: "You agree to use the Service only for lawful purposes. You agree not to submit false or misleading content, attempt to circumvent security features, use bots or scrapers to access the Service, or resell the Service without written consent.",
            },
            {
              title: "4. Intellectual Property",
              body: "The Service and its content are owned by us and protected by applicable intellectual property laws. You retain ownership of the job description content you submit. You own the interview questions and STAR answers generated for you and may use them freely for personal interview preparation purposes.",
            },
            {
              title: "5. No Career or Employment Guarantees",
              body: "We do not guarantee that using our Service will result in job interviews, offers, or any particular career outcome. Interview questions and STAR answers are generated by AI and provided for preparation and informational purposes only. Hiring decisions are made by employers, not by our Service.",
            },
            {
              title: "6. Accuracy of AI-Generated Content",
              body: "Our Service uses AI language models to generate interview questions and answer templates. While we strive for quality and relevance, AI-generated content may contain errors or inaccuracies. You are responsible for reviewing and customizing all AI-generated content before using it in an interview.",
            },
            {
              title: "7. Payments and Refunds",
              body: "The full interview prep pack is available for a one-time payment of $19. Payments are processed securely through Lemon Squeezy. Because the prep pack is delivered instantly as a digital product, all sales are final and non-refundable, except where required by applicable law. If you experience a technical issue preventing delivery, please contact us at bqtools92@gmail.com.",
            },
            {
              title: "8. Limitation of Liability",
              body: "To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid us in the 30 days preceding the claim.",
            },
            {
              title: "9. Disclaimer of Warranties",
              body: 'The Service is provided "as is" and "as available" without warranties of any kind. We expressly disclaim all warranties, including warranties of merchantability, fitness for a particular purpose, and non-infringement.',
            },
            {
              title: "10. Changes to Terms",
              body: "We reserve the right to modify these Terms at any time. Changes are effective immediately upon posting. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms.",
            },
            {
              title: "11. Contact",
              body: "bqtools92@gmail.com",
            },
          ].map((section, i) => (
            <div key={i}>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                {section.title}
              </h2>
              <p
                className={`text-gray-600 ${i === 10 ? "font-semibold text-gray-900" : ""}`}
              >
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
