import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — AI Cover Letter Generator",
  description:
    "Terms of service for Cover Letter Generator. Read our usage terms, payment policy, and legal disclaimers.",
  alternates: {
    canonical: "https://cover-letter-gen-rho.vercel.app/terms",
  },
  robots: { index: false, follow: false },
};

export default function Terms() {
  return (
    <main className="min-h-screen bg-gray-50 py-12 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white rounded-2xl border p-8 space-y-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
            <p className="text-sm text-gray-400">Last updated: June 2025</p>
          </div>

          <p className="text-gray-600">
            These Terms of Service ("Terms") govern your use of the Cover Letter Generator
            website and services ("Service") operated by us. By accessing or using our Service,
            you agree to be bound by these Terms. If you disagree with any part of these Terms,
            please do not use our Service.
          </p>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Description of Service</h2>
            <p className="text-gray-600">
              Cover Letter Generator provides an AI-powered tool that generates a tailored cover
              letter based on a user's resume and a job description. A free preview is available
              to all users. An optional paid tier allows users to unlock, copy, and download the
              full cover letter for a one-time fee of $3.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Eligibility</h2>
            <p className="text-gray-600">
              You must be at least 18 years of age to use this Service. By using the Service, you
              represent that you are at least 18 years old and have the legal capacity to enter
              into these Terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Use of the Service</h2>
            <p className="text-gray-600 mb-3">You agree to use the Service only for lawful purposes. You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 text-gray-600 text-sm">
              <li>Submit content that is false, misleading, defamatory, or violates any third party's rights</li>
              <li>Attempt to circumvent, disable, or interfere with security features of the Service</li>
              <li>Use automated tools, bots, or scrapers to access the Service without written permission</li>
              <li>Resell, sublicense, or commercially exploit the Service without our written consent</li>
              <li>Use the Service for any purpose that violates applicable laws or regulations</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Intellectual Property</h2>
            <p className="text-gray-600">
              The Service and its original content, features, and functionality are owned by us
              and protected by applicable intellectual property laws. You retain ownership of the
              resume and job description content you submit. You own the cover letter generated
              for you and may use it freely for personal job application purposes.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. No Employment Guarantees</h2>
            <p className="text-gray-600">
              We do not guarantee that using our Service will result in job interviews, job offers,
              or any particular employment outcome. Cover letters are generated by AI and are
              provided for informational and enhancement purposes only. You are responsible for
              reviewing all generated content before submitting it in a job application.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Accuracy of AI-Generated Content</h2>
            <p className="text-gray-600">
              Our Service uses AI language models to generate cover letters. While we strive for
              quality, AI-generated content may contain errors, omissions, or inaccuracies. We
              recommend reviewing and editing the output to best represent your experience before
              submitting it to employers.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Payments and Refunds</h2>
            <p className="text-gray-600 mb-3">
              The cover letter unlock is available for a one-time payment of $3. Payments are
              processed securely through Stripe. By completing a purchase, you agree to Stripe's
              terms and conditions.
            </p>
            <p className="text-gray-600">
              Because the cover letter is delivered instantly as a digital product, all sales are
              final and non-refundable, except where required by applicable law. If you experience
              a technical issue that prevents delivery of your cover letter, please contact us at
              bqtools92@gmail.com and we will resolve it promptly.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Limitation of Liability</h2>
            <p className="text-gray-600">
              To the maximum extent permitted by law, we shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of or
              inability to use the Service. Our total liability for any claim arising from use of
              the Service shall not exceed the amount you paid us in the 30 days preceding the
              claim.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Disclaimer of Warranties</h2>
            <p className="text-gray-600">
              The Service is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We expressly disclaim all warranties, including warranties
              of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Changes to Terms</h2>
            <p className="text-gray-600">
              We reserve the right to modify these Terms at any time. Changes will be effective
              immediately upon posting. Your continued use of the Service after changes are posted
              constitutes your acceptance of the updated Terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Governing Law</h2>
            <p className="text-gray-600">
              These Terms shall be governed by and construed in accordance with applicable laws.
              Any disputes arising from these Terms or your use of the Service shall be resolved
              through good-faith negotiation, and if necessary, binding arbitration.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Contact</h2>
            <p className="text-gray-600">
              If you have any questions about these Terms, please contact us:
            </p>
            <p className="text-gray-900 font-semibold mt-2">bqtools92@gmail.com</p>
          </div>
        </div>
      </div>
    </main>
  );
}
